### PR TITLE
Fix tests' expectations for `unauthorized` error code from JDR (should be 401 instead of 500) [BT-179]

### PR DESCRIPTION
**Pull request by grsterin**

### CODE REVIEW

**Review by breilly2 — APPROVED** [review]
👍   Looks good as long as integration tests pass.

**Review by mcovarr — APPROVED** [review]
also 👍 with passing CI

**Comment by grsterin** [comment]
jenkins retest

**Comment by kshakir** [comment]
jenkins retest

**Review by kshakir — APPROVED** [review]

**Pull request merged**
