### PR TITLE
Stop pushing Martha docker image to quay.io. WA-241

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by kshakir** [comment]
Needs to wait for https://github.com/broadinstitute/firecloud-develop/pull/2233 to merge first.

**Comment by kshakir** [comment]
jenkins retest, and let's confirm that the FIAB is using gcr and not quay.

**Review by salonishah11 — CHANGES_REQUESTED** [review]
Can you please also update the references to `quay.io` in README and release-checklist.md?

**Comment by salonishah11** [comment]
So `fiab-start` is pulling the gcr image (https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/44859/console) 🎉 
image

But the `martha-fiab-test-runner` is still using the quay.io image (https://fc-jenkins.dsp-techops.broadinstitute.org/job/martha-fiab-test-runner/196/consoleFull) 😞 
```
Pull test image: quay.io/broadinstitute/martha:ks_stop_push_to_quay
ks_stop_push_to_quay: Pulling from broadinstitute/martha
............
............
..... Pull complete
Digest: sha256:d5d563ed104508d41e96b6df7fa6af03b69f8c711970dd0d005cb3daf1c89d02
Status: Downloaded newer image for quay.io/broadinstitute/martha:ks_stop_push_to_quay
```
It seems we also need to update the martha image in `firecloud-automated-testing` repo [here](https://github.com/broadinstitute/firecloud-automated-testing/blob/f7a464874ec26ff8351fcb987a7707386d6b7646/run-api-tests.sh#L59-L63). I can create a PR for that.

**Comment by salonishah11** [comment]
Created PR to switch from quay to gcr in `firecloud-automated-testing`: [PR-126](https://github.com/broadinstitute/firecloud-automated-testing/pull/126)

**Comment by salonishah11** [comment]
[PR-126](https://github.com/broadinstitute/firecloud-automated-testing/pull/126) in `firecloud-automated-testing` has now been merged!

**Comment by kshakir** [comment]
jenkins retest 🤞

**Review by salonishah11 — APPROVED** [review]

**Comment by kshakir** [comment]
> Pull test image: us.gcr.io/broad-dsp-gcr-public/martha:ks_stop_push_to_quay

via: https://fc-jenkins.dsp-techops.broadinstitute.org/job/martha-fiab-test-runner/203/consoleFull

**Review by rsasch — APPROVED** [review]

**Pull request merged**
