### PR TITLE
Update request logging [BT-508]

### PR DESCRIPTION
**Pull request by breilly2**

### CODE REVIEW

**Comment by jgainerdewar** [comment]
Confirmed that this log line no longer includes anything it shouldn't 🎉 

However, when I tested with a bogus token, the errors printed in my logs did contain that token - when we get a RemoteServerError it contains the full request, and we print the full error object in the logs. I think we need to update `helpers.logAndSendServerError` as well.

**Comment by breilly2** [comment]
@jgainerdewar @mcovarr Back to ready for review. (or not... looks like some tests are failing now 😞 )

**Review by mcovarr — APPROVED** [review]
lgtm

**Review by jgainerdewar — APPROVED** [review]
Retested and confirmed no tokens in logs. 🎉

**Pull request merged**
